import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import { syncUserToDatabase } from "@/lib/sync-user";


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await syncUserToDatabase();
  return (

    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={inter.className} >
        <ClerkProvider>
          {/* header */}
          <Header />
          <div className="min-h-screen flex flex-col">
            {children}
          </div>
          <Footer />
          {/* footer */}
        </ClerkProvider>

      </body>
    </html>
  );
}
